name: linters

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      -
        uses: actions/checkout@v2
      -
        name: dependencies
        run: |
          python -m pip install poetry
          poetry install
      -
        name: install hooks
        run: poetry run pre-commit install-hooks
      -
        name: ${{ matrix.PRE-COMMIT-HOOK }}
        run: poetry run pre-commit run --all-files
