name: tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SOURCES_DIR: sources
    strategy:
      matrix:
        PYTHON-VERSION:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      -
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.PYTHON-VERSION }}
      -
        uses: actions/checkout@v2
      -
        run: |
          python -m pip install poetry
          poetry install --extras cairo
      -
        run: poetry run pytest -vv
