name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCES_DIR: sources
    steps:
    -
      uses: actions/checkout@v2
    -
      name: Python 3.9 installation
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    -
      name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
    -
      name: pytest
      run: poetry run pytest -vv
